export type ModuleStatus = "completed" | "in_progress" | "not_started"

export interface Task {
  id: string
  title: string
  done: boolean
}

export interface Module {
  id: number
  name: string
  status: ModuleStatus
  totalTasks: number
  completedTasks: number
  priority: string
  description: string
  tasks: Task[]
}

export const modules: Module[] = [
  {
    id: 0,
    name: "Foundation",
    status: "completed",
    totalTasks: 12,
    completedTasks: 12,
    priority: "P0",
    description: "Repo scaffold, Django + React setup, Docker, common utilities, CI/CD",
    tasks: [
      { id: "F-01", title: "Repo scaffold: monorepo structure", done: true },
      { id: "F-02", title: "Django project with split settings", done: true },
      { id: "F-03", title: "/api/v1/ router + health endpoint", done: true },
      { id: "F-04", title: "Requirements files (base/local/production)", done: true },
      { id: "F-05", title: "React/Vite + TypeScript scaffold", done: true },
      { id: "F-06", title: "API client with Axios + interceptors", done: true },
      { id: "F-07", title: "Docker Compose setup", done: true },
      { id: "F-08", title: "CORS + JWT configuration", done: true },
      { id: "F-09", title: "Common base models (TimeStamped, TenantScoped)", done: true },
      { id: "F-10", title: "TenantScopedViewSet + permissions", done: true },
      { id: "F-11", title: "Pagination, error handler, constants", done: true },
      { id: "F-12", title: "CI/CD pipeline (lint + tests + coverage)", done: true },
    ],
  },
  {
    id: 1,
    name: "Authentication",
    status: "in_progress",
    totalTasks: 10,
    completedTasks: 2,
    priority: "P0",
    description: "JWT login/logout, user model, role-based routing, protected routes",
    tasks: [
      { id: "A-01", title: "Custom User model with roles", done: true },
      { id: "A-02", title: "Migration + Django admin", done: true },
      { id: "A-03", title: "POST /auth/login/ endpoint", done: false },
      { id: "A-04", title: "Refresh, logout, me endpoints", done: false },
      { id: "A-05", title: "DRF throttling on login", done: false },
      { id: "A-06", title: "Bootstrap business management command", done: false },
      { id: "A-07", title: "Backend auth tests", done: false },
      { id: "A-08", title: "Frontend authStore (Zustand)", done: false },
      { id: "A-09", title: "API client interceptors", done: false },
      { id: "A-10", title: "LoginPage + protected routes", done: false },
    ],
  },
  {
    id: 2,
    name: "Business / Tenant",
    status: "in_progress",
    totalTasks: 6,
    completedTasks: 1,
    priority: "P0",
    description: "Business profile, tenant isolation, multi-tenancy foundation",
    tasks: [
      { id: "B-01", title: "Business model + migration", done: true },
      { id: "B-02", title: "Serializers + tenant-scoped viewset", done: false },
      { id: "B-03", title: "Tenant isolation tests", done: false },
      { id: "B-04", title: "Logo upload placeholder", done: false },
      { id: "B-05", title: "Business profile page + edit form", done: false },
      { id: "B-06", title: "Business store (Zustand)", done: false },
    ],
  },
  {
    id: 3,
    name: "Users & Staff",
    status: "not_started",
    totalTasks: 6,
    completedTasks: 0,
    priority: "P0",
    description: "Staff CRUD, role permission matrix, staff management UI",
    tasks: [
      { id: "U-01", title: "Staff CRUD endpoints", done: false },
      { id: "U-02", title: "Role permission matrix", done: false },
      { id: "U-03", title: "Permission tests", done: false },
      { id: "U-04", title: "Invite/onboard flow", done: false },
      { id: "U-05", title: "Staff management page", done: false },
      { id: "U-06", title: "Login-as-staff smoke check", done: false },
    ],
  },
  {
    id: 4,
    name: "Customers",
    status: "not_started",
    totalTasks: 14,
    completedTasks: 0,
    priority: "P0",
    description: "Customer CRUD, search, filters, detail page with history tabs",
    tasks: [
      { id: "C-01", title: "Customer model", done: false },
      { id: "C-02", title: "Indexes + migration", done: false },
      { id: "C-03", title: "Serializers + validation", done: false },
      { id: "C-04", title: "CRUD viewset", done: false },
      { id: "C-05", title: "Search + filters + pagination", done: false },
      { id: "C-06", title: "Backend tests", done: false },
      { id: "C-07", title: "Customer detail aggregate endpoint", done: false },
      { id: "C-08", title: "Soft-delete semantics", done: false },
      { id: "C-09", title: "Frontend API + types", done: false },
      { id: "C-10", title: "Customers list page", done: false },
      { id: "C-11", title: "Customer form", done: false },
      { id: "C-12", title: "Customer details page", done: false },
      { id: "C-13", title: "Empty states + skeleton loaders", done: false },
      { id: "C-14", title: "Module DoD check", done: false },
    ],
  },
  {
    id: 5,
    name: "Meals",
    status: "not_started",
    totalTasks: 5,
    completedTasks: 0,
    priority: "P0",
    description: "Meal types CRUD (Breakfast, Lunch, Dinner, Snacks)",
    tasks: [
      { id: "M-01", title: "Meal model", done: false },
      { id: "M-02", title: "CRUD endpoints + tests", done: false },
      { id: "M-03", title: "Frontend API + types", done: false },
      { id: "M-04", title: "Meals list page + form", done: false },
      { id: "M-05", title: "Seed defaults", done: false },
    ],
  },
  {
    id: 6,
    name: "Plans",
    status: "not_started",
    totalTasks: 6,
    completedTasks: 0,
    priority: "P0",
    description: "Subscription plans with duration, price, meal type, skip/pause config",
    tasks: [
      { id: "P-01", title: "Plan model", done: false },
      { id: "P-02", title: "Validation rules", done: false },
      { id: "P-03", title: "CRUD endpoints + tests", done: false },
      { id: "P-04", title: "Frontend API + types", done: false },
      { id: "P-05", title: "Plans list + form pages", done: false },
      { id: "P-06", title: "Plan card UI", done: false },
    ],
  },
  {
    id: 7,
    name: "Subscriptions",
    status: "not_started",
    totalTasks: 16,
    completedTasks: 0,
    priority: "P0",
    description: "Core business logic — state machine, create/pause/resume/cancel/renew",
    tasks: [
      { id: "S-01", title: "Subscription model", done: false },
      { id: "S-02", title: "Indexes + migration", done: false },
      { id: "S-03", title: "State machine transitions map", done: false },
      { id: "S-04", title: "Create subscription service", done: false },
      { id: "S-05", title: "API endpoints + filters", done: false },
      { id: "S-06", title: "Pause/resume/cancel actions", done: false },
      { id: "S-07", title: "Renew action", done: false },
      { id: "S-08", title: "Expiring subscriptions selector", done: false },
      { id: "S-09", title: "Remaining days/meals calculators", done: false },
      { id: "S-10", title: "Full transition tests", done: false },
      { id: "S-11", title: "Frontend API + types", done: false },
      { id: "S-12", title: "Subscriptions list page", done: false },
      { id: "S-13", title: "Subscription card UI", done: false },
      { id: "S-14", title: "Subscription form", done: false },
      { id: "S-15", title: "Action dialogs", done: false },
      { id: "S-16", title: "Renewal dialog", done: false },
    ],
  },
  {
    id: 8,
    name: "Payments",
    status: "not_started",
    totalTasks: 12,
    completedTasks: 0,
    priority: "P0",
    description: "Payment recording, activation chain, golden workflow e2e",
    tasks: [
      { id: "PAY-01", title: "Payment model", done: false },
      { id: "PAY-02", title: "Indexes + migration", done: false },
      { id: "PAY-03", title: "Record payment service", done: false },
      { id: "PAY-04", title: "Activation chain (payment → active → deliveries)", done: false },
      { id: "PAY-05", title: "API endpoints", done: false },
      { id: "PAY-06", title: "Payment summary selector", done: false },
      { id: "PAY-07", title: "Payment math tests", done: false },
      { id: "PAY-08", title: "Frontend API + types", done: false },
      { id: "PAY-09", title: "Record payment flow UI", done: false },
      { id: "PAY-10", title: "Payments history page", done: false },
      { id: "PAY-11", title: "Payment summary cards", done: false },
      { id: "PAY-12", title: "Golden workflow e2e test", done: false },
    ],
  },
  {
    id: 9,
    name: "Deliveries + Skip/Pause",
    status: "not_started",
    totalTasks: 16,
    completedTasks: 0,
    priority: "P0",
    description: "Daily delivery tracking, skip meals, pause subscriptions, Celery jobs",
    tasks: [
      { id: "D-01", title: "Delivery model", done: false },
      { id: "D-02", title: "Indexes + migration", done: false },
      { id: "D-03", title: "Generate delivery schedule service", done: false },
      { id: "D-04", title: "Today's deliveries endpoint", done: false },
      { id: "D-05", title: "Delivery status update (staff)", done: false },
      { id: "D-06", title: "Delivery history endpoint", done: false },
      { id: "D-07", title: "MealSkip + SubscriptionPause models", done: false },
      { id: "D-08", title: "Skip flow", done: false },
      { id: "D-09", title: "Configurable skip/pause rules", done: false },
      { id: "D-10", title: "Pause flow", done: false },
      { id: "D-11", title: "Kitchen meal counts endpoint", done: false },
      { id: "D-12", title: "Full delivery tests", done: false },
      { id: "D-13", title: "Celery + Redis wiring", done: false },
      { id: "D-14", title: "Nightly Celery Beat jobs", done: false },
      { id: "D-15", title: "Today's deliveries page", done: false },
      { id: "D-16", title: "Delivery history + kitchen views", done: false },
    ],
  },
  {
    id: 10,
    name: "Dashboard",
    status: "not_started",
    totalTasks: 8,
    completedTasks: 0,
    priority: "P0",
    description: "KPI cards, expiry widget, delivery/payment/meal widgets",
    tasks: [
      { id: "DB-01", title: "Dashboard aggregator endpoint", done: false },
      { id: "DB-02", title: "Tests vs seeded data", done: false },
      { id: "DB-03", title: "Frontend API + types", done: false },
      { id: "DB-04", title: "Dashboard page + StatCards", done: false },
      { id: "DB-05", title: "Expiry widget", done: false },
      { id: "DB-06", title: "Delivery widget", done: false },
      { id: "DB-07", title: "Payment + meal summary widgets", done: false },
      { id: "DB-08", title: "Quick actions (deep-links)", done: false },
    ],
  },
  {
    id: 11,
    name: "Notifications",
    status: "not_started",
    totalTasks: 8,
    completedTasks: 0,
    priority: "P1",
    description: "In-app notifications — payment, subscription, delivery events",
    tasks: [
      { id: "N-01", title: "Notification model", done: false },
      { id: "N-02", title: "NotificationService.emit()", done: false },
      { id: "N-03", title: "Wire emitters from services", done: false },
      { id: "N-04", title: "Nightly expiring/expired job", done: false },
      { id: "N-05", title: "List + mark-read endpoints", done: false },
      { id: "N-06", title: "Notification tests", done: false },
      { id: "N-07", title: "Frontend bell + dropdown", done: false },
      { id: "N-08", title: "Notification preferences stub", done: false },
    ],
  },
  {
    id: 12,
    name: "Reports",
    status: "not_started",
    totalTasks: 9,
    completedTasks: 0,
    priority: "P1",
    description: "Customer, subscription, revenue, meal reports with charts",
    tasks: [
      { id: "R-01", title: "Customer report", done: false },
      { id: "R-02", title: "Subscription report", done: false },
      { id: "R-03", title: "Revenue report", done: false },
      { id: "R-04", title: "Meal report", done: false },
      { id: "R-05", title: "Payment report + date filters", done: false },
      { id: "R-06", title: "Report accuracy tests", done: false },
      { id: "R-07", title: "Reports pages with Recharts", done: false },
      { id: "R-08", title: "Charts + date-range filters", done: false },
      { id: "R-09", title: "CSV export", done: false },
    ],
  },
  {
    id: 13,
    name: "Settings",
    status: "not_started",
    totalTasks: 5,
    completedTasks: 0,
    priority: "P1",
    description: "Business configuration — skip rules, pause rules, delivery window",
    tasks: [
      { id: "ST-01", title: "BusinessSettings model", done: false },
      { id: "ST-02", title: "Settings endpoints + tests", done: false },
      { id: "ST-03", title: "Settings admin UI", done: false },
      { id: "ST-04", title: "Business profile + logo upload", done: false },
      { id: "ST-05", title: "Validation UX for rule changes", done: false },
    ],
  },
  {
    id: 14,
    name: "Audit Trail",
    status: "not_started",
    totalTasks: 3,
    completedTasks: 0,
    priority: "P1",
    description: "Log important admin actions (subscription changes, payments, staff)",
    tasks: [
      { id: "AU-01", title: "AuditLog model", done: false },
      { id: "AU-02", title: "Write hooks from services", done: false },
      { id: "AU-03", title: "Django admin view", done: false },
    ],
  },
  {
    id: 15,
    name: "Customer Portal",
    status: "not_started",
    totalTasks: 11,
    completedTasks: 0,
    priority: "P1",
    description: "Customer self-service — view subscription, skip meal, pause, renew",
    tasks: [
      { id: "PT-01", title: "Customer-role API scoping", done: false },
      { id: "PT-02", title: "Permission tests", done: false },
      { id: "PT-03", title: "Customer portal dashboard", done: false },
      { id: "PT-04", title: "My Subscription page", done: false },
      { id: "PT-05", title: "Payments + delivery history", done: false },
      { id: "PT-06", title: "Profile view/edit", done: false },
      { id: "PT-07", title: "Staff layouts (delivery + kitchen)", done: false },
      { id: "PT-08", title: "Route guards for all roles", done: false },
      { id: "PT-09", title: "DRF throttling", done: false },
      { id: "PT-10", title: "Mobile-responsive pass", done: false },
      { id: "PT-11", title: "Error/toast polish", done: false },
    ],
  },
  {
    id: 16,
    name: "Seed Data & Demo",
    status: "not_started",
    totalTasks: 6,
    completedTasks: 0,
    priority: "P0",
    description: "Demo data, Rahul scenario dry-run, DoD checklist, MVP tag",
    tasks: [
      { id: "SD-01", title: "Seed command (20 customers, 5 plans, etc.)", done: false },
      { id: "SD-02", title: "Reset command", done: false },
      { id: "SD-03", title: "Rahul demo dry-run (12 steps)", done: false },
      { id: "SD-04", title: "Definition of Done checklist", done: false },
      { id: "SD-05", title: "DB backup + restore rehearsal", done: false },
      { id: "SD-06", title: "Final polish + tag v0.1.0-mvp", done: false },
    ],
  },
]
