# Generated by Django 5.2.4 on 2026-09-28 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_alter_business_options'),
        ('customers', '0001_initial'),
        ('meals', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not Delivered'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='customers.customer')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='meals.meal')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['delivery_date', 'customer__name'],
            },
        ),
        migrations.CreateModel(
            name='MealSkip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skip_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='customers.customer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skip_record', to='deliveries.delivery')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-skip_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPause',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['business', 'delivery_date', 'status'], name='idx_delivery_biz_date'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('subscription', 'delivery_date', 'meal'), name='unique_delivery_per_sub_date_meal'),
        ),
    ]
