# Generated by Django 5.2.4 on 2026-09-27 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_alter_business_options'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(help_text='Plan duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_meals', models.PositiveIntegerField(help_text='Total meals included in the plan', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('skip_allowed', models.BooleanField(default=False)),
                ('pause_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='meals.meal')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_plan_name_per_business')],
            },
        ),
    ]
