# Generated by Django 5.2.4 on 2026-09-28 16:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_alter_business_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_skip_days', models.PositiveIntegerField(default=3, help_text='Max skip days per subscription')),
                ('min_pause_days', models.PositiveIntegerField(default=1, help_text='Minimum pause duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_pause_days', models.PositiveIntegerField(default=7, help_text='Maximum pause duration in days')),
                ('skip_rule', models.CharField(choices=[('EXTEND', 'Extend subscription end date'), ('CREDIT', 'Meal credit'), ('NONE', 'No adjustment')], default='NONE', max_length=10)),
                ('delivery_start_time', models.TimeField(blank=True, help_text='Delivery window start', null=True)),
                ('delivery_end_time', models.TimeField(blank=True, help_text='Delivery window end', null=True)),
                ('notify_on_payment', models.BooleanField(default=True)),
                ('notify_on_expiring', models.BooleanField(default=True)),
                ('notify_on_delivery', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'business settings',
            },
        ),
    ]
