"""Delivery API (D-04, D-05, D-06, D-11)."""

from django_filters import rest_framework as django_filters
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from apps.deliveries.models import Delivery
from apps.deliveries.serializers import DeliveryListSerializer, DeliveryStatusUpdateSerializer
from apps.deliveries.services import DeliverySelector, DeliveryService
from common.constants import Role
from common.permissions import RoleBasedPermission
from common.viewsets import TenantScopedViewSet


class DeliveryFilter(django_filters.FilterSet):
    date_from = django_filters.DateFilter(field_name="delivery_date", lookup_expr="gte")
    date_to = django_filters.DateFilter(field_name="delivery_date", lookup_expr="lte")
    status = django_filters.CharFilter(field_name="status")
    customer = django_filters.UUIDFilter(field_name="customer_id")
    subscription = django_filters.UUIDFilter(field_name="subscription_id")
    assigned_staff = django_filters.UUIDFilter(field_name="assigned_staff_id")

    class Meta:
        model = Delivery
        fields = ["status", "customer", "subscription", "assigned_staff"]


class DeliveryViewSet(TenantScopedViewSet):
    """Deliveries: list, today, status update, kitchen counts.

    - OWNER/MANAGER: full access.
    - DELIVERY_STAFF: view assigned + update status.
    - KITCHEN_STAFF: view kitchen counts only.
    - No create/delete — generated by DeliveryService.
    """

    queryset = Delivery.objects.select_related("customer", "meal", "assigned_staff").all()
    serializer_class = DeliveryListSerializer
    permission_classes = [IsAuthenticated, RoleBasedPermission]
    filterset_class = DeliveryFilter
    http_method_names = ["get", "post", "patch", "head", "options"]

    role_map = {
        "list": [Role.OWNER, Role.MANAGER, Role.DELIVERY_STAFF, Role.KITCHEN_STAFF],
        "retrieve": [Role.OWNER, Role.MANAGER, Role.DELIVERY_STAFF, Role.KITCHEN_STAFF],
        "today": [Role.OWNER, Role.MANAGER, Role.DELIVERY_STAFF],
        "update_status": [Role.OWNER, Role.MANAGER, Role.DELIVERY_STAFF],
        "skip": [Role.OWNER, Role.MANAGER],
        "kitchen_counts": [Role.OWNER, Role.MANAGER, Role.KITCHEN_STAFF],
    }

    @action(detail=False, methods=["get"])
    def today(self, request):
        """GET /deliveries/today/ — today's deliveries."""
        qs = DeliverySelector.get_today(request.user.business_id)
        page = self.paginate_queryset(qs)
        if page is not None:
            serializer = DeliveryListSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        serializer = DeliveryListSerializer(qs, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=["patch"], url_path="status")
    def update_status(self, request, pk=None):
        """PATCH /deliveries/{id}/status/ — update delivery status."""
        delivery = self.get_object()
        serializer = DeliveryStatusUpdateSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        try:
            delivery = DeliveryService.update_status(
                delivery,
                serializer.validated_data["status"],
                notes=serializer.validated_data.get("notes", ""),
            )
        except ValueError as e:
            return Response(
                {"error": {"code": "INVALID_TRANSITION", "message": str(e), "fields": {}}},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(DeliveryListSerializer(delivery).data)

    @action(detail=True, methods=["post"])
    def skip(self, request, pk=None):
        """POST /deliveries/{id}/skip/ — skip this delivery."""
        delivery = self.get_object()
        reason = request.data.get("reason", "")
        try:
            skip = DeliveryService.skip_meal(delivery, reason=reason)
        except ValueError as e:
            return Response(
                {"error": {"code": "VALIDATION_ERROR", "message": str(e), "fields": {}}},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response({"id": str(skip.id), "skip_date": str(skip.skip_date), "reason": skip.reason})

    @action(detail=False, methods=["get"])
    def kitchen_counts(self, request):
        """GET /deliveries/kitchen_counts/ — today's meal totals."""
        counts = DeliverySelector.get_kitchen_counts(request.user.business_id)
        return Response(list(counts))
