# Generated by Django 5.2.4 on 2026-09-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name_plural': 'businesses'},
        ),
    ]
